language: python
python:
  - "3.6"
script:
  - chmod +x bin/build.sh 
  - bin/build.sh
deploy:
  provider: script
  script: bash bin/deploy.sh
  skip_cleanup: true
  keep_history: true
  on:
    branch: master
